### ISSUE TITLE
After migration in subwiki: list of imported pages is usually empty

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/application-confluence-migrator-pro#67] opened 2024-02-12 15:20 UTC
If a migration has been finished, it displays a section: "The imported pages from the N selected Confluence Space(s)", together with a clickable list of these spaces. Selecting one of these spaces should open the navigation tree of for the imported pages for that space.

This works in the main wiki, but when importing in a subwiki, it calls the tree with  `root: "document:xwiki:SPACE.WebHome"` i.e.tries to look up the data from the main wiki, which gives the wrong result (usually "no pages found", unless there is a space with the same name in the main wiki).

**Comment by ClemensRobbenhaar** [comment] 2024-02-13 19:14
I ran the migrator on a subwiki. The migrator was also installed on the mail wiki, if that makes a difference.

If you cannot reproduce the issue, feel free to close as "not reproducible", maybe I did mess up something with my setup.

**Comment by trrenty** [comment] 2024-03-04 13:06
We had a similar issue opened here #24 . 

I tested it again for good measure.

I took the following steps in order to test the issue:

1. Installed the migrator on the main wiki.
2. Performed a migration in order to check that everything works fine
3. Created a subwiki
4. Installed the migrator on the said subwiki
5. Performed a migration using a different package to check that everything works fine

On both the main  wiki and the subwiki the `Imported spaces` navigation trees functioned as expected.

I will close the issue as `Could not reproduce`.

**Closed by trrenty** 2024-03-04 13:06 UTC
